/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem.gui;

import inventorysystem.Events.LoginEvent;
import inventorysystem.Events.Request;
import inventorysystem.Interface.LoginImplementation;
import inventorysystem.Interface.LoginInterface;
import inventorysystem.data.Employee;
import inventorysystem.data.Login;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import inventorysystem.InventorySystem;
import inventorysystem.Interface.Switchable;
import inventorysystem.data.SalesEmployee;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Epic
 */
public class login extends javax.swing.JPanel implements Switchable, LoginInterface {

    private static boolean loggedIn = false;
    private Employee currentEmployee = null;
    /**
     * Creates new form login
     */
    private Request _requestEvent;

    public login(Request r) {
        initComponents();
        this.setName("Login Panel");
        _requestEvent = r;
        _requestEvent.addLoginListener(new LoginImplementation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblWrong = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password:");

        btnLogin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inventory System for Group 1");

        lblWrong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblWrong.setForeground(new java.awt.Color(255, 0, 0));
        lblWrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWrong.setText("Wrong user credentials");
        lblWrong.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(lblWrong)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        performLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            performLogin();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

// <editor-fold defaultstate="collapsed" desc="Initialize variables">       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblWrong;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
//</editor-fold>

    @Override
    public void OnPanelSwitched(JPanel panelToSwitch) {
        try {
            InventorySystem.switchPanel(panelToSwitch, loggedIn);

        } catch (Exception ex) {
            Logger.getLogger(login.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("I have been called oh bro to change the panel " + panelToSwitch.getName());
    }

    public static boolean isLoggedIn() {
        return loggedIn;
    }

    public Employee getCurrentEmployee() {
        return currentEmployee;
    }

    private static final Logger LOG = Logger.getLogger(login.class
            .getName());

    @Override
    public void handleEvent(LoginEvent event) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void performLogin() {
        if (!txtPassword.getText().isEmpty() && !txtUsername.getText().isEmpty()) {
            Login l = new Login();
            this.currentEmployee = l.isUser(txtUsername.getText(), txtPassword.getText());

            if (null != this.currentEmployee) {
                _requestEvent._fireEvents(new LoginEvent(this, currentEmployee)); // tell the listener to save the name of the employee saved
                //_requestEvent.addLoginListener(new Products(_requestEvent));
                lblWrong.setVisible(false);
                JOptionPane.showMessageDialog(null, "Welcome ".concat(this.currentEmployee.getUsername()));
                loggedIn = true;

                //Goto new panel on the block
                setUserScreen();
            } else {
                lblWrong.setVisible(true);
            }
        }
    }
    /**
     * Set up screen according to the currently logged in user type
     */
    private void setUserScreen(){
        if(this.currentEmployee instanceof SalesEmployee){
            this.OnPanelSwitched(new Sales());
        }else{
            this.OnPanelSwitched(new Dashboard());
        }
    }
}
